name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment virables
      env:
        # LOCATION points the parent directory
        LOCATION_SETUP_PY: src # optional. for pypi upload
      run: |
        echo "::set-env name=LOCATION_SETUP_PY::$LOCATION_SETUP_PY"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: |
        cd $LOCATION_SETUP_PY
        python setup.py sdist bdist_wheel

    - name: Lint
      run: |
        echo "Lint ... None"
        # fail test or pass test
    - name: Slack
      if: always()
      uses: 8398a7/action-slack@v3.2.0
      with:
        status: ${{job.status}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Github Action Slack
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}